input {
  file {
    path => [
      "/cowrie/logs1/cowrie.json",
      "/cowrie/logs2/cowrie.json",
      "/cowrie/logs3/cowrie.json"
    ]
    start_position => "beginning"
    sincedb_path => "/dev/null"
  }
}

filter {
  json {
    source => "message"
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "cowrie-logs"
  }
  stdout { codec => rubydebug }
}